### ISSUE TITLE
Remove "Scan" statement from Print information [label: suggestion]

### ISSUE THREAD

**Issue by wujastyk** [PanditProject/Website#30]
![image](https://user-images.githubusercontent.com/762246/128056265-335d5ca4-7c56-464c-a4e2-0703a879abc4.png)

The existence of a scan is treated differently in the Related MSS and Print listings.  The black dot is sufficient and efficient and the same display style should be extended to Print items too. 

@AmirSimantov

**Comment by AmirSimantov** [comment]
Dear Dominik, please supply links to the said entity/entities. Thanks.

**Comment by wujastyk** [comment]
[https://www.panditproject.org/entity/99168/work](https://www.panditproject.org/entity/99168/work)

**Comment by AmirSimantov** [comment]
Thanks for the link, Dominik.

Regarding the "contained in" field in the "Related manuscripts" box:
The big black dot may be sufficient to _you_, Dominik because you were the one who asked for this feature. That dot by itself isn't self-explained; another reader might not guess what it stands for. So, although I understand your wish for a minimal presentation, we have to think about serving other users' needs.
If there is one scan, it says "1 scan";  if there are multiple scans, we tell how much, e.g., "2 scans."

Regarding the "Scholarship" field in the "Print sources" box:
The word "Scan" means that the "Data text format" is a simple scan, not "Scan encoded." If you have a better word or a short term, we can use them.

Dominik, we are now short on resources, so we tend not to put much effort into presentation issues; instead, we focus on structure, needed fields, and some important behavior features.

**Comment by wujastyk** [comment]
Yes, I take your point about the black dot :-)  

My point was really just that the visual syntax of the same information in the two boxes (Contained in & Scholarship) is different and that's confusing. 

Since you mention it, I have no idea what "data text format" means.  Nor "scan encoded".  Neither of these expressions have I seen before.  I would assume that I'm not untypical as a user.

Regarding resources, once an issue is opened, Github provides ways of triaging things, assigning them to specific people for attention, promoting or demoting them, etc., etc.  Just because there's an issue here, it doesn't mean there is pressure on you to attend to it.  You can put things on the back burner for later :-).  For example, you could create a label "presentational issues", and leave those for a more appropriate time.

**Comment by AmirSimantov** [comment]
I am glad you understand the big dot issue; we should always think about the rest.

In each of the entity editing forms where we have the "Data text format" field, there is a big colored box explaining what it means. Here how it looks like:
<img width="1090" alt="Screen Shot 2021-08-17 at 10 23 25" src="https://user-images.githubusercontent.com/10967743/129754714-2d84af33-d798-4962-b87a-3d8c37507a08.png">

Again, if you think that wording in the **presentation** layer isn't clear enough, please suggest other wording.

Managing the issues also takes time. Again, Yigal is short of resources now. I know how issue-trackers work, how labels work, etc.

Dominik, we have also explained that we don't have the mandate to "assign" users for an issue. They aren't our employees, nor gave us a permission for that. This is something you can discuss with @ybronner.
