### ISSUE TITLE
Can't insert "Dates"

### ISSUE THREAD

**Issue by chakrabortydeepro** [PanditProject/Website#65]
It does not allow you to simply type the dates, you need to select from a number list. 

![image](https://github.com/user-attachments/assets/4f14885a-1d5f-4d77-940b-a38cecbaf9bb)

**Comment by roikedem** [comment]
Hi @chakrabortydeepro, thanks for your comment! Can you please share which operating system (windows/mac etc. or mobile phone) and which browser you are using (chrome, edge, safari)? If it happens on a certain page, can you please write its address?
Can you take a screenshot of the list you mentioned?
I am asking because I can't find the problem: I type the number of the year using the keyboard.

**Comment by chakrabortydeepro** [comment]
Thanks for your comment, Roi. I just rechecked it and it is working now. I was working on the entry of [Udayarāja](https://panditproject.org/node/114146) and I could not type the date directly.  I am using Linux Mint and Chrome. I don't know why I could not add the date at that time. Nevermind! Sorry for the trouble.
