### ISSUE TITLE
Site entries do not display "mentioned in works"

### ISSUE THREAD

**Issue by chakrabortydeepro** [PanditProject/Website#66]
Works that mention sites do not appear in the entity Site. For example, [Lampaka](https://panditproject.org/node/114152), a site mentioned in [Laghupañcikā](https://panditproject.org/entity/108983/work). You can find Lampaka in the Laghupañcikā entry but  Laghupañcikā does not appear in Lampaka.

**Comment by roikedem** [comment]
@chakrabortydeepro 
Thanks for your input, I fixed the display of entities of type "Site"

**Comment by chakrabortydeepro** [comment]
Thanks, Roi. There is an error on the entires I mentioned in my message but when I am trying to correct it I'm getting this message "The website encountered an unexpected error. Try again later."

**Comment by roikedem** [comment]
@chakrabortydeepro Deepro, thanks, you helped to find an important bug. I fixed it.

The bug was entered when I changed the code to fix the problem that @wujastyk complained about - the need to remove multi-value fields (such as Scholarship, Resources, Editions, etc.) on newly-created entities. So now you can just fill in the fields that are relevant to your new entity, less hassle for content contributors.

Roi

**Comment by chakrabortydeepro** [comment]
It is all good now. Thanks, Roi.
